#!/usr/bin/env node

// Bundles the exact-pinned @hydradb/sdk (plus its runtime deps form-data and
// node-fetch) into ONE self-contained ESM file at scripts/vendor/hydradb-sdk.mjs.
//
// Why this exists: this plugin ships through a PUBLIC Claude Code marketplace,
// which installs by `git clone` with NO `npm install`. A bare `import
// "@hydradb/sdk"` therefore throws ERR_MODULE_NOT_FOUND at module-load time and
// crashes every hook before any guard runs. The vendored bundle is a plain
// committed file imported by relative path, so the plugin RUNTIME stays
// zero-dependency; esbuild is a build-time devDependency only.
//
// Regenerate with `npm run build:vendor` (or `make vendor`) after any SDK bump.
// check.mjs asserts the committed bundle is byte-identical to a fresh build, so
// an SDK bump without a re-bundle fails CI.

import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const sdkVersion = require(path.join(root, "node_modules/@hydradb/sdk/package.json")).version;
const pinnedVersion = require(path.join(root, "package.json")).devDependencies?.["@hydradb/sdk"];

if (pinnedVersion && sdkVersion !== pinnedVersion) {
  process.stderr.write(
    `build-vendor: installed @hydradb/sdk (${sdkVersion}) does not match the pinned ` +
      `devDependency (${pinnedVersion}). Run \`npm install\` before vendoring.\n`
  );
  process.exit(1);
}

// The SDK's dist is TypeScript-compiled CJS that defines its named exports via
// runtime getters under an `__esModule` marker. `export * from` cannot statically
// enumerate those, so we read the actual runtime keys and emit explicit named
// re-exports - which also captures whatever a future pinned SDK version exposes.
const sdkExportNames = Object.keys(require("@hydradb/sdk")).filter((name) => name !== "default");
if (!sdkExportNames.length) {
  process.stderr.write("build-vendor: @hydradb/sdk exposed no named exports - refusing to emit an empty bundle.\n");
  process.exit(1);
}

// `--out <path>` lets check.mjs build to a temp file for a byte-identical
// drift comparison without clobbering the committed bundle.
const outFlagIndex = process.argv.indexOf("--out");
const outfile =
  outFlagIndex !== -1 && process.argv[outFlagIndex + 1]
    ? path.resolve(process.argv[outFlagIndex + 1])
    : path.join(root, "scripts/vendor/hydradb-sdk.mjs");

const banner = [
  `// @generated by scripts/build-vendor.mjs - DO NOT EDIT BY HAND.`,
  `// Self-contained bundle of @hydradb/sdk@${sdkVersion} (+ form-data, node-fetch).`,
  `// Regenerate with \`npm run build:vendor\`; check.mjs guards against drift.`
].join("\n");

await esbuild.build({
  stdin: {
    // Re-export the SDK's public surface. The wrapper imports from this file,
    // never from "@hydradb/sdk" directly.
    contents: `export { ${sdkExportNames.join(", ")} } from "@hydradb/sdk";\n`,
    resolveDir: root,
    loader: "js",
    sourcefile: "vendor-entry.js"
  },
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  outfile,
  legalComments: "none",
  banner: { js: banner },
  logLevel: "warning"
});

process.stdout.write(`Vendored @hydradb/sdk@${sdkVersion} → ${path.relative(root, outfile)}\n`);
